# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            JayChen
tagline:          '个人博客'

author:
  name:           'JayChen'
  url:            https://ijaychen.github.io

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
